apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: scpro-elmis-prescriptions-pipeline
  namespace: flink-jobs
spec:
  deploymentName: session-cluster
  job:
    jarURI: https://github.com/IHMAfrica/zm-scpro-elmis-prescriptions-pipeline/releases/download/latest/zm-scpro-elmis-prescriptions-pipeline-all.jar
    entryClass: zm.gov.moh.hie.scp.Main
    parallelism: 3
    upgradeMode: stateless
    state: running
    args:
      - "--jdbc.url=jdbc:postgresql://172.16.20.9:35616/hie_manager"
      - "--kafka.group.id=scpro-elmis-prescriptions-pipeline"
